'use client';

import { useState } from 'react';
import MapUI from '@/components/MapUI';
import ControlPanel from '@/components/ControlPanel';
import { SimulationProvider } from '@/lib/SimulationContext';

export default function Home() {
  const [isServerActive, setIsServerActive] = useState(true);
  const [showManual, setShowManual] = useState(false);

  const testTrigger = async () => {
    try {
      const res = await fetch('/api/orchestrator', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          agentId: 'Judge_Test_Agent_' + Math.floor(Math.random() * 1000),
          lat: 40.7580 + (Math.random() - 0.5) * 0.05,
          lng: -73.9855 + (Math.random() - 0.5) * 0.05,
          defaultTask: 'Exploring NYC',
        }),
      });
      if (!res.ok) throw new Error(`Spawn failed: ${res.status}`);
      console.log(await res.json());
    } catch (e) {
      console.error('Failed to spawn test NPC:', e);
    }
  };

  return (
    <SimulationProvider enabled={isServerActive}>
    <main className="flex h-screen w-screen bg-black overflow-hidden flex-col md:flex-row relative">

      {/* USER MANUAL MODAL */}
      {showManual && (
        <div className="absolute inset-0 z-50 flex items-center justify-center p-8 bg-black/80 backdrop-blur-sm">
          <div className="bg-[#0d0f14] border border-gray-800 rounded-lg max-w-3xl w-full max-h-[90vh] overflow-y-auto shadow-2xl animate-in fade-in zoom-in duration-300 flex flex-col">
            <div className="sticky top-0 bg-[#0d0f14] border-b border-gray-800 p-6 flex justify-between items-center z-10">
              <h2 className="text-2xl font-black text-white tracking-tighter">METROPOLIS <span className="text-emerald-500">USER MANUAL</span></h2>
              <button onClick={() => setShowManual(false)} className="text-gray-500 hover:text-white transition-colors">✕</button>
            </div>

            <div className="p-8 space-y-8 text-gray-300 font-mono text-sm leading-relaxed">
              <section>
                <h3 className="text-emerald-400 font-bold mb-3 border-b border-gray-800 pb-2">1. The Simulation (Google Maximalism)</h3>
                <p>Welcome to Metropolis. You are viewing a live, autonomous agentic simulation running across NYC. Every NPC on the map is powered by a continuous Temporal.io workflow querying <strong>Gemini 3.0 Flash</strong>.</p>
                <p className="mt-2">The agents are grounded in physical reality via <strong>Google Search</strong> and the <strong>OpenWeather API</strong>—if it rains in real life, they react.</p>
              </section>

              <section>
                <h3 className="text-emerald-400 font-bold mb-3 border-b border-gray-800 pb-2">2. Interacting with the UI</h3>
                <ul className="list-disc pl-5 space-y-2">
                  <li><strong>Map Detail Panel:</strong> Click on any glowing node (Agent) on the map. This opens the detail panel displaying their role, internal cognitive goal, real-time sentiment, and a <strong>Google Street View</strong> snapshot of their precise coordinates.</li>
                  <li><strong>Global Stats:</strong> The Control Panel to the right streams global telemetry straight from Firestore: total active entities, interaction count, and a global sentiment average.</li>
                  <li><strong>NLP Stream:</strong> As agents cross paths (&lt;50 meters), an encounter is triggered. The dialogue is generated by Gemini and evaluated by the <strong>Google Cloud Natural Language API</strong>.</li>
                </ul>
              </section>

              <section>
                <h3 className="text-emerald-400 font-bold mb-3 border-b border-gray-800 pb-2">3. Vertex AI Semantic Memory</h3>
                <p>When agents meet, they don't just chat randomly. The Orchestrator uses <strong>Vertex AI (text-embedding-004)</strong> to analyze both agents' recent histories. It calculates cosine similarity to find shared concepts, injecting "meaningful context" into the Gemini prompt right before they speak.</p>
              </section>

              <section>
                <h3 className="text-rose-400 font-bold mb-3 border-b border-gray-800 pb-2">4. Testing Durability</h3>
                <p>Click the <strong className="text-rose-500">"KILL PROCESS"</strong> button in the top right. This simulates a total crash of the Next.js server. Notice the UI greys out. The agents don't die—their state is perfectly preserved in Firestore. Click <strong className="text-emerald-500">"RESTORE ENGINE"</strong> to instantly resume the simulation from the exact state.</p>
              </section>
            </div>

            <div className="mt-auto p-6 border-t border-gray-800 bg-gray-900/50 flex justify-end">
              <button onClick={() => setShowManual(false)} className="px-6 py-2 bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 rounded font-bold hover:bg-emerald-500 hover:text-white transition-colors">Start Simulation</button>
            </div>
          </div>
        </div>
      )}

      {/* 
        By pausing the UI connection when the server is "killed", 
        we simulate the agent's logic pausing until restoration, perfectly demoing durability. 
      */}
      <div className={`flex-grow h-1/2 md:h-full transition-opacity duration-1000 relative ${isServerActive ? 'opacity-100' : 'opacity-20 pointer-events-none blur-sm'}`}>
        <MapUI />

        {/* Help Button overlaid on map */}
        <button
          onClick={() => setShowManual(true)}
          className="absolute bottom-6 left-6 z-40 px-4 py-2 bg-black/80 backdrop-blur-md border border-gray-700 text-gray-300 font-mono text-xs rounded hover:bg-gray-800 hover:text-white transition-colors shadow-lg flex items-center gap-2"
        >
          <span className="w-4 h-4 rounded-full border border-current flex items-center justify-center font-bold">?</span>
          User Manual
        </button>
      </div>

      <div className="w-full md:w-[450px] h-1/2 md:h-full border-t md:border-t-0 md:border-l border-gray-700 bg-gray-900 shadow-xl flex flex-col relative z-20">
        <ControlPanel
          onSimulateKill={() => setIsServerActive(false)}
          onRestart={() => setIsServerActive(true)}
        />

        <div className="p-6 bg-gray-800 border-t border-gray-700 font-mono text-sm text-gray-400 flex justify-between items-center">
          <div>Status: <span className={isServerActive ? "text-green-400 font-bold" : "text-red-500 font-bold mb-4"}>{isServerActive ? "ONLINE" : "OFFLINE"}</span></div>
          <button onClick={testTrigger} className="px-3 py-1 bg-purple-600 hover:bg-purple-700 text-white rounded text-xs transition-colors">
            Spawn Test NPC
          </button>
        </div>
      </div>
    </main>
    </SimulationProvider>
  );
}
